# Generated by Django 5.1.2 on 2024-10-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='id',
            new_name='i_d',
        ),
    ]
