# Generated by Django 5.1.2 on 2024-10-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_rename_id_author_i_d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='i_d',
            new_name='id',
        ),
    ]
