# Generated by Django 5.1.2 on 2024-11-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_tag_remove_quote_tags_quote_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
